### ISSUE TITLE
Make recurring payments subscriptions configurable

### ISSUE THREAD

**Issue by bumi** [bumi/area402-widget#36]
We should support an option to disable the email subscriptions.

**Comment by reznord** [comment]
What do you want the default behavior to be? Should we allow it by default and give an option to disable the email subscriptions or the other way around?

**Comment by bumi** [comment]
I'd disable it by default for now because it will take a bit to get the backend right and we can publish the widget without it. 
And then later change the default to enable it.

**Comment by reznord** [comment]
Sure

**Comment by reznord** [comment]
Will be going with `enableEmailSubscription` as the key
