### ISSUE TITLE
Widget accessibility from global scope

### ISSUE THREAD

**Issue by reznord** [bumi/area402-widget#57]
We should be able to access the widget from the global scope. So, the end-users should be able to do:

```
window.area402.open()
```

**Comment by bumi** [comment]
and we should allow the user to pass in configuration props to the `open()` function.

**Comment by reznord** [comment]
> and we should allow the user to pass in configuration props to the open() function.

Should be doable but then we will be putting all the values in the local state and consuming from there instead of the props.

**Comment by reznord** [comment]
IMO, even if we want to add support for that, we should be doing that in a separate PR since this is already a bit huge.
