### ISSUE TITLE
Amount inputs in one row

### ISSUE THREAD

**Issue by bumi** [bumi/area402-widget#58]
Currently we have the custom amount input pretty big in the second line. 
I think we should make it smaller and also put it in the first row.

![image](https://user-images.githubusercontent.com/318/101333666-2b151e00-3877-11eb-9847-73db8fb037ce.png)

what do you think?

**Comment by bumi** [comment]
if we have those as floating elements then it would automatically break into multiple rows depending on the width of the parent element? I think that would be best.

**Comment by reznord** [comment]
yeah, true. I agree but then when you want to show an error message below the custom input field for amount validation, it will  look bad there.

**Comment by bumi** [comment]
true, that's currently also the problem. we should have the Euro sign there on the right - as the preselected values have - and maybe simple a __ as placeholder... indicating people can add a custom value. 

The error messages should be a global error message anyway, meaning only a message and not specific to a field.
