### ISSUE TITLE
Add reset css styles

### ISSUE THREAD

**Issue by bumi** [bumi/area402-widget#6]
As the widget is embedded in various different websites with various different styles we need to add some reset css to make sure the widget's style is added from scratch. 

~~Is [normalize.css](https://necolas.github.io/normalize.css/) still the way to go here? ~~ I think we rather want some reset css that clears all styles and we style everything custom from scratch - and not from some normalized basic css.

**Comment by bumi** [comment]
this example includes a custom reset: https://github.com/Tyler-Churchill/Embeddable-Widget-Preact-Typescript/blob/master/src/Widget.tsx#L10-L14

**Comment by bumi** [comment]
https://github.com/csstools/postcss-normalize

**Comment by bumi** [comment]
probably rather this one: https://github.com/maximkoretskiy/postcss-autoreset

**Comment by bumi** [comment]
I actually think we want a combination of setting an initial CSS value (does not work in IE11) https://developer.mozilla.org/en-US/docs/Web/CSS/initial
and a reset

**Comment by reznord** [comment]
> this example includes a custom reset: https://github.com/Tyler-Churchill/Embeddable-Widget-Preact-Typescript/blob/master/src/Widget.tsx#L10-L14

This is a good option to explore. But I'm not sure if this would work on modal or not because the modals are rendered directly on the body.

**Comment by reznord** [comment]
Can be closed now because of #7
