### ISSUE TITLE
Directly jump to the payment screen if an amount is provided as propery

### ISSUE THREAD

**Issue by bumi** [bumi/area402-widget#69]
If an amount is provided in the props we should directly request an invoice and jump to the payment screen when the widget is opened.

example usage: 
```
<a href="javascript:window.area402.openWidget(amount: 1)"><a>
```

though that also means we might need some additional loading spinner that we show while we request the invoice.

**Comment by reznord** [comment]
Just an FYI:

`javascript:window.area402.openWidget()` takes an object. as of now, in that case, I need to manually check for the amount key if is present or not and then directly skip to the payment screen.

**Comment by bumi** [comment]
can't this be done in the general constructor/init process? so whenever an amount prop is set we do that?

**Comment by reznord** [comment]
By the time you are trying to open the widget using `javascript:window.area402.openWidget()` the whole component is already initialized and the constructor is invoked already.

There's another way to do this,  which I am exploring now.
