### ISSUE TITLE
Background SVGs prevent text selection

### ISSUE THREAD

**Issue by bumi** [bumi/area402-widget#72]
It seems the background SVGs overlap other elements and prevent for example that the text in the input field can be selected or the "copy" icon can be clicked.

I think maybe we can simply use a background image (via CSS) and not a SVG?

**Comment by reznord** [comment]
Weird.....it seems to be working when I was implementing the UI. Will look into it today.

**Comment by bumi** [comment]
it depends on the size of the widget and where it overlays maybe?
but eitherway I was wondering if we can't simply use a CSS background image?

**Comment by bumi** [comment]
actually I think we can simply remove the background for now.

**Comment by reznord** [comment]
I would hold on this because the text selection issue can be solved easily setting `z-index: -1` on `TopCircleWrapper` and `BottomCircleWrapper`
